coolsms:
  api:
    key: "NCSJC9B1CTYZFSM1"
    secret: "QHBMBQLX6BBX8V8FEYX1VWUDR7OK4OYW"

spring:
  sql:
    init:
      mode: always
      data-locations: classpath:sql/schema2.sql
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: laptopgyutti28@gmail.com
    password: ntcmqjwulmbwvlap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: 1234

jpa:
  open-in-view: true
  hibernate:
    #show_sql: true
    #format_sql: true
    ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  defer-datasource-initialization: true
  properties:
    hibernate.format_sql: true
    dialect: org.hibernate.dialect.MySQL8InnoDBDialect



logging:
  level:
    org.hibernate.SQL: debug


