server:
  port: 8080

coolsms:
  api:
    key: "NCSJC9B1CTYZFSM1"
    secret: "QHBMBQLX6BBX8V8FEYX1VWUDR7OK4OYW"

spring:
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: springtestgyutti28@gmail.com
    password: idxckqegnbdozicf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: gyuja

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  accessTokenExpirationMinutes: 860000
  refreshTokenExpirationMinutes: 1600000
